{
 "title": "Hue Motion Sensor",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "room", "query": { "query": "hue_motion_sensor_temperature" } }
  ]
 },
 "panels": [
  {
   "title": "État Salon",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hue_motion_sensor_state{room=\"Salon\"}"
    }
   ]
  },
  {
   "title": "Batterie restante Salon",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hue_motion_sensor_battery{room=\"Salon\"}"
    }
   ]
  },
  {
   "title": "Température  Salon",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hue_motion_sensor_temperature{room=\"Salon\"}/100"
    }
   ]
  },
  {
   "title": "Luminosité Salon",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(hue_motion_sensor_lightlevel{room=\"Salon\"})"
    }
   ]
  },
  {
   "title": "État Véranda",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hue_motion_sensor_state{room=\"Véranda\"}"
    }
   ]
  },
  {
   "title": "Batterie restante Véranda",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hue_motion_sensor_battery{room=\"Véranda\"}"
    }
   ]
  },
  {
   "title": "Température  Véranda",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hue_motion_sensor_temperature{room=\"Véranda\"}/100"
    }
   ]
  },
  {
   "title": "Luminosité Véranda",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(hue_motion_sensor_lightlevel{room=\"Véranda\"})"
    }
   ]
  },
  {
   "title": "Évolution de la température",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(hue_motion_sensor_temperature{room=~\"$room\"}/100) by (room)",
     "legendFormat": "{{room}}"
    }
   ]
  },
  {
   "title": "Évolution de la luminosité",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "expr": "sum(hue_motion_sensor_lightlevel{room=~\"$room\"}) by (room)",
     "legendFormat": "{{room}}"
    }
   ]
  },
  {
   "title": "Détection de mouvement",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(hue_motion_sensor_presence{room=~\"$room\"}) by (room)",
     "legendFormat": "{{room}}"
    }
   ]
  }
 ]
}